"""v2_data_intelligence_fields

Revision ID: 952d680e7005
Revises: 
Create Date: 2026-03-31 00:03:20.917052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952d680e7005'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('parser_config', sa.Text(), nullable=True),
    sa.Column('auth_config', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('proxy_url', sa.String(length=500), nullable=True),
    sa.Column('custom_headers', sa.Text(), nullable=True),
    sa.Column('trust_level', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleaned_content', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('quality_tag', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('needs_llm_matching', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('keyword_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id_a', sa.Integer(), nullable=False),
    sa.Column('keyword_id_b', sa.Integer(), nullable=False),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=False),
    sa.Column('relationship_desc', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id_a'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['keyword_id_b'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id_a', 'keyword_id_b', 'period_start', 'period_end')
    )
    op.create_table('trend_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_drivers', sa.JSON(), nullable=True),
    sa.Column('outlook', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'report_date', 'period')
    )
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'date', name='uq_keyword_date')
    )
    op.create_table('keyword_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('match_location', sa.String(length=20), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_mentions')
    op.drop_table('trend_snapshots')
    op.drop_table('trend_reports')
    op.drop_table('keyword_correlations')
    op.drop_table('articles')
    op.drop_table('alerts')
    op.drop_table('keywords')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
